/**
 * Debug: Compare our cycles with the reference
 * 
 * Reference from user:
 * R: cycles [3, 39, 48, 21], [6, 42, 51, 24], [9, 45, 54, 27]
 * 
 * Our R cycles:
 * [21, 9, 43, 48], [24, 6, 40, 51], [27, 3, 37, 54]
 * 
 * Let me trace what the reference says vs what we have
 */

console.log("=== Comparing R move cycles ===\n")
console.log("Reference cycles (from user):")
console.log("  [3, 39, 48, 21] - meaning 3→39→48→21→3")
console.log("  [6, 42, 51, 24]")
console.log("  [9, 45, 54, 27]")
console.log("")
console.log("Our cycles:")
console.log("  [21, 9, 43, 48] - meaning 21→9→43→48→21")
console.log("  [24, 6, 40, 51]")
console.log("  [27, 3, 37, 54]")
console.log("")
console.log("=== Problem identified! ===")
console.log("Reference uses B col: 39, 42, 45 (right column of B)")
console.log("We're using B col: 37, 40, 43 (left column of B)")
console.log("")
console.log("Let's check which column of B touches R:")
console.log("")
console.log("Layout:")
console.log("[ R (Right)] [ B (Back) ]")
console.log("28  29  30   37  38  39")
console.log("31  32  33   40  41  42")
console.log("34  35  36   43  44  45")
console.log("")
console.log("R's right column (30, 33, 36) is physically at the BACK-RIGHT of the cube")
console.log("B's LEFT column (37, 40, 43) is at the BACK-RIGHT of the cube")
console.log("")
console.log("But wait! When R moves CW, it doesn't touch B's edge at all!")
console.log("R's back edge goes to U, and U's back edge goes to B...")
console.log("")
console.log("Let me re-trace R move:")
console.log("- R face is on the RIGHT of the cube")
console.log("- R col0 (28, 31, 34) is FRONT-RIGHT of cube")
console.log("- R col2 (30, 33, 36) is BACK-RIGHT of cube")
console.log("")
console.log("When R rotates CW (looking from right):")
console.log("- F col2 (21, 24, 27) goes UP to U col2 (3, 6, 9)")
console.log("- U col2 (3, 6, 9) goes BACK to B... but which part of B?")
console.log("")
console.log("B face layout (as seen from BEHIND the cube):")
console.log("37  38  39   <- this row touches U row0")
console.log("40  41  42")
console.log("43  44  45   <- this row touches D row2")
console.log("")
console.log("B col0 (37, 40, 43) is on the LEFT side when looking at B from behind")
console.log("But physically, this is the RIGHT side of the cube (same side as R)!")
console.log("")
console.log("U col2 (3, 6, 9) when going to B:")
console.log("U[3] is at (row0, col2) = BACK-RIGHT of U")
console.log("This should connect to B's TOP-LEFT corner (37)")
console.log("")
console.log("Hmm, but the reference says R uses [3, 39, 48, 21]")
console.log("39 is at B's TOP-RIGHT corner...")
console.log("")
console.log("Maybe the reference uses a different B orientation?")
console.log("In Kociemba's original convention, B might be mirrored!")
console.log("")
console.log("Let me check: if B is read left-to-right WHEN LOOKING FROM BEHIND:")
console.log("Then B[37] = back-top-LEFT, B[39] = back-top-RIGHT")
console.log("And R's back edge should connect to B's LEFT column (37, 40, 43)")
console.log("")
console.log("But if B is read left-to-right WHEN LOOKING FROM FRONT (through the cube):")
console.log("Then B[37] = back-top-RIGHT, B[39] = back-top-LEFT")
console.log("And R's back edge should connect to B's RIGHT column (39, 42, 45)")
console.log("")
console.log("The reference uses 39, 42, 45 for R, so it assumes B is read from FRONT!")

console.log("\n\n=== SOLUTION ===")
console.log("We need to swap our B column indices!")
console.log("")
console.log("For R move:")
console.log("  Old: [21, 9, 43, 48], [24, 6, 40, 51], [27, 3, 37, 54]")
console.log("  New: [21, 9, 45, 48], [24, 6, 42, 51], [27, 3, 39, 54]")
console.log("  Or following reference format: [3, 39, 48, 21], [6, 42, 51, 24], [9, 45, 54, 27]")
console.log("")
console.log("Similarly for L move (uses B col2 in our current, should use B col0):")
console.log("  Old: [1, 19, 46, 45], [4, 22, 49, 42], [7, 25, 52, 39]")  
console.log("  New: [1, 19, 46, 43], [4, 22, 49, 40], [7, 25, 52, 37]")
