/**
 * Deriving correct cube move cycles from first principles
 *
 * Physical cube layout:
 * - U (Up) face: white, row0 is BACK, row2 is FRONT
 * - D (Down) face: yellow, row0 is FRONT, row2 is BACK
 * - F (Front) face: green
 * - B (Back) face: blue, appears "mirrored" in unfolded view
 * - R (Right) face: red
 * - L (Left) face: orange
 *
 * Key insight: B face's left side touches R, B's right side touches L
 * In unfolded layout, B appears as if you're looking from behind
 */

// For each move, trace the physical ring of stickers that rotates

console.log('=== F MOVE ===')
console.log('F rotates CW when looking at front face')
console.log('Ring around F: U row2, R col0, D row0, L col2')
console.log('')
console.log('Physical positions (cube corners/edges):')
console.log('- U[2][0] = Front-Left-Top corner')
console.log('- U[2][1] = Front-Top edge')
console.log('- U[2][2] = Front-Right-Top corner')
console.log('')
console.log('- R[0][0] = Front-Right-Top corner')
console.log('- R[1][0] = Front-Right edge')
console.log('- R[2][0] = Front-Right-Bottom corner')
console.log('')
console.log('- D[0][0] = Front-Left-Bottom corner')
console.log('- D[0][1] = Front-Bottom edge')
console.log('- D[0][2] = Front-Right-Bottom corner')
console.log('')
console.log('- L[0][2] = Front-Left-Top corner')
console.log('- L[1][2] = Front-Left edge')
console.log('- L[2][2] = Front-Left-Bottom corner')
console.log('')
console.log('When F rotates CW (looking at front):')
console.log('Front-Left-Top -> Front-Right-Top: U[2][0] -> R[0][0]')
console.log('Front-Right-Top -> Front-Right-Bottom: R[0][0] -> D[0][2]')
console.log('Front-Right-Bottom -> Front-Left-Bottom: D[0][2] -> L[2][2]')
console.log('Front-Left-Bottom -> Front-Left-Top: L[2][2] -> U[2][0]')
console.log('')
console.log('Full mapping:')
console.log('U[2][0] -> R[0][0], U[2][1] -> R[1][0], U[2][2] -> R[2][0]')
console.log('R[0][0] -> D[0][2], R[1][0] -> D[0][1], R[2][0] -> D[0][0]')
console.log('D[0][0] -> L[2][2], D[0][1] -> L[1][2], D[0][2] -> L[0][2]')
console.log('L[0][2] -> U[2][2], L[1][2] -> U[2][1], L[2][2] -> U[2][0]')

console.log('\n=== B MOVE ===')
console.log('B rotates CW when looking at back face (from behind)')
console.log('Ring around B: U row0, R col2, D row2, L col0')
console.log('')
console.log('Physical positions:')
console.log('- U[0][0] = Back-Left-Top corner')
console.log('- U[0][1] = Back-Top edge')
console.log('- U[0][2] = Back-Right-Top corner')
console.log('')
console.log('- R[0][2] = Back-Right-Top corner')
console.log('- R[1][2] = Back-Right edge')
console.log('- R[2][2] = Back-Right-Bottom corner')
console.log('')
console.log('- D[2][0] = Back-Left-Bottom corner')
console.log('- D[2][1] = Back-Bottom edge')
console.log('- D[2][2] = Back-Right-Bottom corner')
console.log('')
console.log('- L[0][0] = Back-Left-Top corner')
console.log('- L[1][0] = Back-Left edge')
console.log('- L[2][0] = Back-Left-Bottom corner')
console.log('')
console.log('When B rotates CW (looking from behind):')
console.log("Back-Left-Top -> Back-Right-Top: wait, that's CCW from behind view!")
console.log('')
console.log('Actually, looking at the cube from BEHIND, CW rotation means:')
console.log('Back-Right-Top -> Back-Right-Bottom -> Back-Left-Bottom -> Back-Left-Top')
console.log('Which is: U[0][2] -> R[0][2] ... no wait')
console.log('')
console.log('Let me think again. When standing BEHIND the cube looking at B face:')
console.log("- What's on my LEFT is the cube's RIGHT side (R face)")
console.log("- What's on my RIGHT is the cube's LEFT side (L face)")
console.log("- What's on TOP is still TOP (U face)")
console.log("- What's on BOTTOM is still BOTTOM (D face)")
console.log('')
console.log('CW rotation from behind: pieces move U -> L -> D -> R -> U (from behind view)')
console.log('Which from FRONT view means: U -> L -> D -> R -> U')
console.log('')
console.log('So: U[0][2] (back-right-top) -> L[0][0] (back-left-top when viewed from behind)')
console.log('Wait no. Let me trace carefully:')
console.log('')
console.log('Standing behind the cube, B face is in front of me.')
console.log("B's top edge touches U's row 0 (which is the back of U)")
console.log("B's right edge (from behind view) touches L's col 0 (cube's left side)")
console.log("B's bottom edge touches D's row 2 (which is the back of D)")
console.log("B's left edge (from behind view) touches R's col 2 (cube's right side)")
console.log('')
console.log(
  'When B rotates CW (from behind), the ring goes: U row0 -> R col2 -> D row2 -> L col0 -> U row0',
)
console.log('')
console.log('Mapping positions:')
console.log('U[0][2] (back-right-top) -> R[0][2] (back-right-top on R face)')
console.log('U[0][1] (back-top edge) -> R[1][2] (back-right edge)')
console.log('U[0][0] (back-left-top) -> R[2][2] (back-right-bottom on R face)')
console.log('')
console.log('R[0][2] -> D[2][2] (back-right-bottom)')
console.log('R[1][2] -> D[2][1] (back-bottom edge)')
console.log('R[2][2] -> D[2][0] (back-left-bottom)')
console.log('')
console.log('D[2][2] -> L[2][0] (back-left-bottom on L)')
console.log('D[2][1] -> L[1][0] (back-left edge)')
console.log('D[2][0] -> L[0][0] (back-left-top on L)')
console.log('')
console.log('L[0][0] -> U[0][0] (back-left-top)')
console.log('L[1][0] -> U[0][1] (back-top edge)')
console.log('L[2][0] -> U[0][2] (back-right-top)')
